name: KAP Pay Geri Alımı Bot

on:
  schedule:
    - cron: "*/5 * * * *"   # her 5 dakikada bir (GitHub limiti için ideal)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Paketler
        run: pip install requests

      - name: Çalıştır
        run: python app.py
        env:
          KAP_API_KEY: ${{ secrets.KAP_API_KEY }}
          KAP_API_SECRET: ${{ secrets.KAP_API_SECRET }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
